# Generated by Django 3.1.4 on 2021-01-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210111_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='plany', max_length=250, verbose_name='name'),
            preserve_default=False,
        ),
    ]
